# site settings
title: Liquid Perfection 
subtitle: 
email: liquidperfectionjax@gmail.com
description: 	<h3>GET A FREE ESTIMATE!</h3> <input type=hidden name='captcha_settings' value='{"keyname":"liquidperfectionjax","fallback":"true","orgId":"00DDn000007qQ3h","ts":""}'><input type=hidden name="oid" value="00DDn000007qQ3h"><input type=hidden name="retURL" value="http://liquidperfectionjax.net/thankyou.html"><label for="first_name">First Name</label><input id="first_name" maxlength="40" name="first_name" size="20" type="text" /><br><label for="email">Email</label><input id="email" maxlength="80" name="email" size="20" type="text" /><br><label for="phone">Phone</label><input id="phone" maxlength="40" name="phone" size="20" type="text" /><br>Coating:<select id="00NDn00000TOi3I" name="00NDn00000TOi3I" title="Coating"><option value="">--None--</option><option value="Solid">Solid</option><option value="Flake">Flake</option><option value="Reflector">Reflector</option><option value="Custom">Custom</option></select><br><div class="g-recaptcha" data-sitekey="6LcNIyIkAAAAAAjfhbg6ARS8H6Qi9O8WgFWgbX_v"></div><br><input type="submit" name="submit"></form>
baseurl: "/liquidperfectionjax" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 3051 Waters View Circle
city: Orange Park
state: FL
zip_code: 32073
country: United States of America
phone: (904) 329-5312

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: 
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: 
  Twitter: 
  Facebook: https://www.facebook.com/Liquid-Perfection-1374511976188884/
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
