# site settings
title: Liquid Perfection 
subtitle: 
email: liquidperfectionjax@gmail.com
description: 	<h3>GET A FREE ESTIMATE!</h3> <form action="https://webto.salesforce.com/servlet/servlet.WebToLead?encoding=UTF-8" method="POST"><input type=hidden name='captcha_settings' value='{"keyname":"liquidperfectionjax","fallback":"true","orgId":"00DDn000007qQ3h","ts":""}'><input type=hidden name="oid" value="00DDn000007qQ3h"><input type=hidden name="retURL" value="http://liquidperfectionjax.net/thankyou.html"><div class="row uniform"><div class="6u 12u$(xsmall)"><input type="text" name="first_name" id="first_name" value="" placeholder="Name" required /></div><div class="6u$ 12u$(xsmall)"><input type="email" name="email" id="email" value="" placeholder="Email" required /></div><div class="6u$ 12u$(xsmall)"><input type="tel" name="phone" id="phone" value="" placeholder="Phone" required /></div><div class="12u$"><div class="select-wrapper"><label for="00NDn00000TOi3I">Coating Type:</label><select name="00NDn00000TOi3I" id="00NDn00000TOi3I"><option value="Solid">Solid&trade</option><option value="Flake">Flake</option><option value="Reflector">Reflector</option><option value="Custom">Custom</option></select></div></div><div class="g-recaptcha" data-sitekey="6LcNIyIkAAAAAAjfhbg6ARS8H6Qi9O8WgFWgbX_v"></div><br><div class="12u$"><ul class="actions"><li><input type="submit" name="submit" value="GET FREE ESTIMATE!" class="special" /></li></ul></div></div></form>
baseurl: "/liquidperfectionjax" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 3051 Waters View Circle
city: Orange Park
state: FL
zip_code: 32073
country: United States of America
phone: (904) 329-5312

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: 
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: 
  Twitter: 
  Facebook: https://www.facebook.com/Liquid-Perfection-1374511976188884/
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
